spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:unimanage}
    username: ${DB_USER:postgres}
    password: ${DB_PASS:admin}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  sql:
    init:
      mode: always
      platform: postgres
#      schema-locations: scheme.sql

server:
  port: 8443
  ssl:
    key-store: classpath:keystore.p12
    key-store-password: unimanage #todo : use in .env
    key-store-type: PKCS12
    key-alias: myapp



app:
  security:
    jwt:
      access-token-expiration: 86400000
      refresh-token-expiration: 604800000



