spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/unimanage   # replace 'mydb' with your database name
    username: postgres                             # replace with your postgres user
    password: admin                         # replace with your postgres password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create     # options: none | validate | update | create | create-drop
    show-sql: true         # logs SQL queries in the console
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  sql:
    init:
      mode: always         # runs schema/data.sql at startup if present
      platform: postgres

server:
  port: 8080
